[site]
title = "You Li"
description = "Incoming Ph.D. student at Fudan University."
favicon = "/favicon-32.png"
last_updated = "February 27, 2026"

[author]
name = "You Li 李由"
title = "RA / Incoming Ph.D. Student"
institution = "Fudan University"
avatar = "/avatar.jpg"

[social]
email = "youli@alu.fudan.edu.cn"
location = "Shanghai, China"
location_details = [
  "579 Guoquan Road",
  "School of Data Science, Fudan University",
  "Shanghai, China"
]
github = "https://github.com/Reason-You"
linkedin = "https://www.linkedin.com/in/you-li-122765185/"
google_scholar = "https://scholar.google.com/citations?user=L4F0vw4AAAAJ&hl=zh-CN"

[features]
enable_likes = true
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Research"
type = "page"
target = "research"
href = "/research"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
