[[news]]
date = "2026-01"
content = "I have accepted my Ph.D. offer from Fudan University (starting in September 2026)."

[[news]]
date = "2025-09"
content = "Started as a Research Assistant at FDU-VIS Lab and began leading projects."

[[news]]
date = "2025-06"
content = "I earned my Master's Degree from Fudan University."